# Generated by Django 3.0.1 on 2020-12-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upd',
            name='image',
        ),
        migrations.AddField(
            model_name='upd',
            name='im',
            field=models.ImageField(default='django.jpg', upload_to='Profile_pics/'),
        ),
    ]
