# Generated by Django 3.0.1 on 2020-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=5)),
                ('mailid', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=5)),
                ('body', models.CharField(max_length=5)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('language', models.CharField(blank=True, choices=[('T', 'Telugu'), ('E', 'English'), ('H', 'Hindi')], max_length=1, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
