# Generated by Django 3.0.1 on 2020-12-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_student_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
