# Generated by Django 3.0.1 on 2020-12-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('Python', 'Python')], max_length=30, null=True),
        ),
    ]
